# Generated by Django 4.2 on 2023-04-14 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mixtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('genre', models.CharField()),
                ('channel_source', models.CharField()),
                ('source_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('artwork_url', models.URLField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('release_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('moods', models.ManyToManyField(related_name='mixtapes', to='moods.mood')),
            ],
        ),
    ]
